version: '3'

services:
  backend:
    build:
      context: './Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
